Add endnotes and some marker styling
unfoldingWord-box3/simple-text-editor-rcl pull request #5
Opened 2021-12-02 19:28 UTC by RUN-Projects

2021-12-06 19:35 UTC, klappy requested changes
Can you remove the .hidden clause in the CSS? 
That should be an app concern. We can work up some examples later for preview that allow what you need to be hidden.

2021-12-07 00:40 UTC, RUN-Projects commented
Yes; Hadn't meant for that to slip in the rcl css as it isn't used.
The marker.s5 green and marker.s5 red style should probably also be remove unless there is a reason to single out s5 -- is there?
Also, should this head towards an empty `\s#` or empty `\s` being styled red, with a completed `\s#` or `\s` being styled either in the same manner in a related styles that reflect the #?

2021-12-07 18:51 UTC, klappy commented
Can you make the change and push the commit? I'll finish reviewing it and merge after testing.

2021-12-09 18:35 UTC, klappy approved these changes

2021-12-09 18:35 UTC, merged